apiVersion: v1
kind: Service
metadata:
  name: sample-python-app-svc
spec:
  selector:
    app: sample-python-app
  ports:
    - protocol: TCP
      port: 80 # Port the service will be available on within the cluster
      targetPort: 5000 # Port the application is listening on in the pods
  type: NodePort # Or ClusterIP if you plan to use Ingress exclusively
                 # NodePort makes it easy to test directly on Pi's IP
